/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Banner = {
  _type: 'banner'
  heading?: string
  subheading?: string
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type ArticleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'article'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'article'
  href?: string
  article?: ArticleReference
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'article'
        href?: string
        article?: ArticleReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type BlockContentProjects = Array<
  | {
      textList?: Array<{
        heading?: string
        text: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        _type: 'textListItem'
        _key: string
      }>
      _type: 'textList'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
  | {
      subheading?: string
      _type: 'subheading'
      _key: string
    }
  | {
      bodyText?: BlockContentTextOnly
      _type: 'bodyText'
      _key: string
    }
>

export type ArticleTag = {
  _id: string
  _type: 'articleTag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type ProjectsPage = {
  _id: string
  _type: 'projectsPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
}

export type PersonalProjectsPage = {
  _id: string
  _type: 'personalProjectsPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
}

export type ServiceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'service'
}

export type CapabilitiesPage = {
  _id: string
  _type: 'capabilitiesPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  capabilities?: Array<
    {
      _key: string
    } & ServiceReference
  >
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  banner?: Banner
  featuredProjects?: Array<{
    project: ProjectReference
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _type: 'featuredProject'
    _key: string
  }>
  featuredServices?: Array<{
    service: ServiceReference
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    _type: 'featuredService'
    _key: string
  }>
  featuredArticles?: Array<
    {
      _key: string
    } & ArticleReference
  >
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  company: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  overview?: string
  projectScope?: Array<string>
  service?: ServiceReference
  date?: string
  content?: BlockContentProjects
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description: string
  capabilities: Array<{
    title: string
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    _type: 'capability'
    _key: string
  }>
}

export type ArticlesPage = {
  _id: string
  _type: 'articlesPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  greeting: BlockContentTextOnly
  personalStatement: BlockContentTextOnly
  profileImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  traits?: Array<{
    title: string
    description: string
    icon: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _type: 'trait'
    _key: string
  }>
  toolbox?: {
    icon: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    tools?: Array<{
      title: string
      text: string
      _type: 'tool'
      _key: string
    }>
  }
  educationDevelopment?: Array<{
    year: string
    title: string
    text: string
    _type: 'educationDevelopmentItem'
    _key: string
  }>
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  Footer?: {
    footerText?: string
    footerEmail?: string
    icon?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    footerLinks?: Array<{
      type?: 'linkedin' | 'twitter' | 'instagram'
      link?: Link
      _type: 'footerLink'
      _key: string
    }>
  }
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'article'
      href?: string
      article?: ArticleReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type ArticleTagReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'articleTag'
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  tags?: Array<
    {
      _key: string
    } & ArticleTagReference
  >
  description?: string
  readTime?: string
  content: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  date?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Banner
  | ArticleReference
  | Link
  | CallToAction
  | SanityImageCrop
  | SanityImageHotspot
  | Button
  | BlockContentTextOnly
  | InfoSection
  | BlockContent
  | BlockContentProjects
  | ArticleTag
  | Slug
  | ProjectsPage
  | PersonalProjectsPage
  | ServiceReference
  | CapabilitiesPage
  | ProjectReference
  | HomePage
  | Project
  | Service
  | ArticlesPage
  | AboutPage
  | Settings
  | ArticleTagReference
  | Article
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  Footer?: {
    footerText?: string
    footerEmail?: string
    icon?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    footerLinks?: Array<{
      type?: 'instagram' | 'linkedin' | 'twitter'
      link?: Link
      _type: 'footerLink'
      _key: string
    }>
  }
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'article' | 'href'
      href?: string
      article?: ArticleReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
} | null

// Source: sanity/lib/queries.ts
// Variable: getAboutPageQuery
// Query: *[_type == 'aboutPage'][0]{    _id,    _type,    title,    greeting,    personalStatement,    profileImage,    traits,    toolbox,    educationDevelopment  }
export type GetAboutPageQueryResult = {
  _id: string
  _type: 'aboutPage'
  title: string
  greeting: BlockContentTextOnly
  personalStatement: BlockContentTextOnly
  profileImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  traits: Array<{
    title: string
    description: string
    icon: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _type: 'trait'
    _key: string
  }> | null
  toolbox: {
    icon: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    tools?: Array<{
      title: string
      text: string
      _type: 'tool'
      _key: string
    }>
  } | null
  educationDevelopment: Array<{
    year: string
    title: string
    text: string
    _type: 'educationDevelopmentItem'
    _key: string
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: getArticlesPageQuery
// Query: *[_type == 'articlesPage'][0]{    _id,    _type,    title,  }
export type GetArticlesPageQueryResult = {
  _id: string
  _type: 'articlesPage'
  title: string
} | null

// Source: sanity/lib/queries.ts
// Variable: getCapabilitiesPageQuery
// Query: *[_type == 'capabilitiesPage'][0]{    _id,    _type,    title,    capabilities[]->{      _id,      _type,      title,      slug,      description,      icon    }  }
export type GetCapabilitiesPageQueryResult = {
  _id: string
  _type: 'capabilitiesPage'
  title: string
  capabilities: Array<{
    _id: string
    _type: 'service'
    title: string
    slug: null
    description: string
    icon: null
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: getHomePageQuery
// Query: *[_type == 'homePage'][0]{    ...,    featuredProjects[]{      ...,      "project": project->{        _id,        _type,        title,        slug,      },    },    featuredServices[]{      ...,      service->{        _id,        _type,        title,        description,        slug,      },    },    featuredArticles[]->{      ...,    },  }
export type GetHomePageQueryResult = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  banner?: Banner
  featuredProjects: Array<{
    project: {
      _id: string
      _type: 'project'
      title: string
      slug: Slug
    }
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    _type: 'featuredProject'
    _key: string
  }> | null
  featuredServices: Array<{
    service: {
      _id: string
      _type: 'service'
      title: string
      description: string
      slug: null
    }
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    _type: 'featuredService'
    _key: string
  }> | null
  featuredArticles: Array<{
    _id: string
    _type: 'article'
    _createdAt: string
    _updatedAt: string
    _rev: string
    title: string
    slug: Slug
    tags?: Array<
      {
        _key: string
      } & ArticleTagReference
    >
    description?: string
    readTime?: string
    content: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    date?: string
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: getProjectsPageQuery
// Query: *[_type == 'projectsPage'][0]{    ...,  }
export type GetProjectsPageQueryResult = {
  _id: string
  _type: 'projectsPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
} | null

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {        ...,        button {          ...,            link {      ...,        _type == "link" => {    "page": page->slug.current,    "article": article->slug.current  }      }        }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "article": article->slug.current  }          }        }      },    },  }
export type GetPageQueryResult = null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "page" || _type == "article" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<{
  slug: string
  _type: 'article'
  _updatedAt: string
}>

// Source: sanity/lib/queries.ts
// Variable: allArticlesQuery
// Query: *[_type == "article" && defined(slug.current)] | order(date desc, _updatedAt desc) {      ...,  }
export type AllArticlesQueryResult = Array<{
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  tags?: Array<
    {
      _key: string
    } & ArticleTagReference
  >
  description?: string
  readTime?: string
  content: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  date?: string
}>

// Source: sanity/lib/queries.ts
// Variable: moreArticlesQuery
// Query: *[_type == "article" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      ...,  }
export type MoreArticlesQueryResult = Array<{
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  tags?: Array<
    {
      _key: string
    } & ArticleTagReference
  >
  description?: string
  readTime?: string
  content: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  date?: string
}>

// Source: sanity/lib/queries.ts
// Variable: articleQuery
// Query: *[_type == "article" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "page": page->slug.current,    "article": article->slug.current  }    }  },      ...,  }
export type ArticleQueryResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  tags?: Array<
    {
      _key: string
    } & ArticleTagReference
  >
  description?: string
  readTime?: string
  date?: string
} | null

// Source: sanity/lib/queries.ts
// Variable: articlePagesSlugs
// Query: *[_type == "article" && defined(slug.current)]  {"slug": slug.current}
export type ArticlePagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<never>

// Source: sanity/lib/queries.ts
// Variable: allProjectsQuery
// Query: *[_type == "project" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  company,  coverImage,  overview,  projectScope,  service{   ...  },  date,  content,  }
export type AllProjectsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string | null
  company: string
  overview: string | null
  projectScope: Array<string> | null
  service: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
  } | null
  content: BlockContentProjects | null
}>

// Source: sanity/lib/queries.ts
// Variable: moreProjectsQuery
// Query: *[_type == "project" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  company,  coverImage,  overview,  projectScope,  service{   ...  },  date,  content,  }
export type MoreProjectsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string | null
  company: string
  overview: string | null
  projectScope: Array<string> | null
  service: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
  } | null
  content: BlockContentProjects | null
}>

// Source: sanity/lib/queries.ts
// Variable: projectQuery
// Query: *[_type == "project" && slug.current == $slug] [0] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  company,  coverImage,  overview,  projectScope,  service{   ...  },  date,  content,  }
export type ProjectQueryResult = {
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string | null
  company: string
  overview: string | null
  projectScope: Array<string> | null
  service: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
  } | null
  content: BlockContentProjects | null
} | null

// Source: sanity/lib/queries.ts
// Variable: projectPagesSlugs
// Query: *[_type == "project" && defined(slug.current)]  {"slug": slug.current}
export type ProjectPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: allServicesQuery
// Query: *[_type == "service"] | order(date desc, _updatedAt desc) {     _id,  _type,  title,  description,  slug,  capabilities[]{    ...,    _type == "capability" => {      ...,      description[]{        ...,        markDefs[]{          ...,            _type == "link" => {    "page": page->slug.current,    "article": article->slug.current  }        }      }    },  },  }
export type AllServicesQueryResult = Array<{
  _id: string
  _type: 'service'
  title: string
  description: string
  slug: null
  capabilities: Array<{
    title: string
    description: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs: Array<{
        href?: string
        _type: 'link'
        _key: string
        page: null
        article: null
      }> | null
      level?: number
      _type: 'block'
      _key: string
    }>
    _type: 'capability'
    _key: string
  }>
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    "\n  *[_type == 'aboutPage'][0]{\n    _id,\n    _type,\n    title,\n    greeting,\n    personalStatement,\n    profileImage,\n    traits,\n    toolbox,\n    educationDevelopment\n  }\n": GetAboutPageQueryResult
    "\n  *[_type == 'articlesPage'][0]{\n    _id,\n    _type,\n    title,\n  }\n": GetArticlesPageQueryResult
    "\n  *[_type == 'capabilitiesPage'][0]{\n    _id,\n    _type,\n    title,\n    capabilities[]->{\n      _id,\n      _type,\n      title,\n      slug,\n      description,\n      icon\n    }\n  }\n": GetCapabilitiesPageQueryResult
    '\n  *[_type == \'homePage\'][0]{\n    ...,\n    featuredProjects[]{\n      ...,\n      "project": project->{\n        _id,\n        _type,\n        title,\n        slug,\n      },\n    },\n    featuredServices[]{\n      ...,\n      service->{\n        _id,\n        _type,\n        title,\n        description,\n        slug,\n      },\n    },\n    featuredArticles[]->{\n    \n  ...,\n\n    },\n  }\n': GetHomePageQueryResult
    "\n  *[_type == 'projectsPage'][0]{\n    ...,\n  }\n": GetProjectsPageQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        ...,\n        button {\n          ...,\n          \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "article": article->slug.current\n  }\n\n      }\n\n        }\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "article": article->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" || _type == "article" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "article" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  ...,\n\n  }\n': AllArticlesQueryResult
    '\n  *[_type == "article" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  ...,\n\n  }\n': MoreArticlesQueryResult
    '\n  *[_type == "article" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "article": article->slug.current\n  }\n\n    }\n  },\n    \n  ...,\n\n  }\n': ArticleQueryResult
    '\n  *[_type == "article" && defined(slug.current)]\n  {"slug": slug.current}\n': ArticlePagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n  *[_type == "project" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  company,\n  coverImage,\n  overview,\n  projectScope,\n  service{\n   ...\n  },\n  date,\n  content,\n\n  }\n': AllProjectsQueryResult
    '\n  *[_type == "project" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  company,\n  coverImage,\n  overview,\n  projectScope,\n  service{\n   ...\n  },\n  date,\n  content,\n\n  }\n': MoreProjectsQueryResult
    '\n  *[_type == "project" && slug.current == $slug] [0] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  company,\n  coverImage,\n  overview,\n  projectScope,\n  service{\n   ...\n  },\n  date,\n  content,\n\n  }\n': ProjectQueryResult
    '\n  *[_type == "project" && defined(slug.current)]\n  {"slug": slug.current}\n': ProjectPagesSlugsResult
    '\n  *[_type == "service"] | order(date desc, _updatedAt desc) {\n   \n  _id,\n  _type,\n  title,\n  description,\n  slug,\n  capabilities[]{\n    ...,\n    _type == "capability" => {\n      ...,\n      description[]{\n        ...,\n        markDefs[]{\n          ...,\n          \n  _type == "link" => {\n    "page": page->slug.current,\n    "article": article->slug.current\n  }\n\n        }\n      }\n    },\n  },\n\n  }\n': AllServicesQueryResult
  }
}
